# Generated by Django 6.1.1 on 2026-09-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evento_organizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='limite_diario_horas',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=5),
        ),
    ]
